version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:12.6-browsers
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: |
            yarn install:dependencies
      - run:
          name: Build MUI
          command: yarn build
      - run:
          name: Verify MUI Artifacts
          command: yarn test