version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: |
            yarn install:dependencies
      - run:
          name: Build MUI
          command: yarn build
      - run:
          name: Verify MUI Artifacts
          command: yarn test
      - persist_to_workspace:
          root: .
          paths:
            - symbols

  publish:
    docker:
      - image: circleci/node:12.6-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command:  |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish @pxblue/symbols-mui
          command: yarn publish:package -b $CIRCLE_BRANCH

workflows:
  version: 2
  colors:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
